Repository matterpoll/matterpoll, pull requests merged in 2018-10, with the labels that each got.

#80 Lock to 5.4 release branch
  server/Gopkg.lock
  server/Gopkg.toml
Labels: 4. to release, bug

#51 Add poll settings
  README.md
  server/command.go
  server/command_test.go
  server/poll.go
  server/poll_test.go
  server/utils.go
  server/utils_test.go
Labels: 3. to review

#79 Move away from test global api objects
  server/api_test.go
  server/command_test.go
  server/configuration_test.go
Labels: 4. to release, technical debt

#81 Sync read and write to config
  server/Gopkg.lock
  server/Gopkg.toml
  server/api.go
  server/command.go
  server/command_test.go
  server/configuration.go
  server/configuration_test.go
  server/plugin.go
  server/plugin_test.go
  server/poll.go
  server/utils.go
  server/versions.go
Labels: 4. to release, bug

#82 Enforce minimum server version
  README.md
  server/Gopkg.lock
  server/Gopkg.toml
  server/api.go
  server/plugin.go
  server/plugin_test.go
Labels: 4. to release, enhancement

#87 Add indicator for poll settings
  server/command_test.go
  server/poll.go
Labels: 4. to release, enhancement

#88 Update Mattermost to v5.4
  build/manifest/Gopkg.lock
  build/manifest/Gopkg.toml
  build/manifest/vendor/github.com/mattermost/mattermost-server/NOTICE.txt
  build/manifest/vendor/github.com/mattermost/mattermost-server/model/authorize.go
  build/manifest/vendor/github.com/mattermost/mattermost-server/model/channel.go
  build/manifest/vendor/github.com/mattermost/mattermost-server/model/channel_member.go
  build/manifest/vendor/github.com/mattermost/mattermost-server/model/client4.go
  build/manifest/vendor/github.com/mattermost/mattermost-server/model/config.go
  build/manifest/vendor/github.com/mattermost/mattermost-server/model/incoming_webhook.go
  build/manifest/vendor/github.com/mattermost/mattermost-server/model/license.go
  build/manifest/vendor/github.com/mattermost/mattermost-server/model/outgoing_webhook.go
  build/manifest/vendor/github.com/mattermost/mattermost-server/model/post.go
  build/manifest/vendor/github.com/mattermost/mattermost-server/model/preference.go
  build/manifest/vendor/github.com/mattermost/mattermost-server/model/role.go
  build/manifest/vendor/github.com/mattermost/mattermost-server/model/search_params.go
  build/manifest/vendor/github.com/mattermost/mattermost-server/model/slack_attachment.go
  build/manifest/vendor/github.com/mattermost/mattermost-server/model/team.go
  build/manifest/vendor/github.com/mattermost/mattermost-server/model/team_member.go
  build/manifest/vendor/github.com/mattermost/mattermost-server/model/terms_of_service.go
  build/manifest/vendor/github.com/mattermost/mattermost-server/model/user.go
  build/manifest/vendor/github.com/mattermost/mattermost-server/model/utils.go
  build/manifest/vendor/github.com/mattermost/mattermost-server/model/version.go
  build/manifest/vendor/github.com/mattermost/mattermost-server/scripts/license-check.sh
  build/manifest/vendor/github.com/mattermost/mattermost-server/utils/markdown/html_entities.go
  server/Gopkg.lock
  server/Gopkg.toml
Labels: 4. to release

#89 Packages
  build/manifest/main.go
  server/command_test.go
  server/main.go
  server/plugin/api.go
  server/plugin/api_test.go
  server/plugin/command.go
  server/plugin/command_test.go
  server/plugin/configuration.go
  server/plugin/configuration_test.go
  server/plugin/manifest.go
  server/plugin/plugin.go
  server/plugin/plugin_test.go
  server/plugin/versions.go
  server/poll/poll.go
  server/poll/poll_test.go
  server/poll/transform.go
  server/poll/transform_test.go
  server/utils/testutils/data.go
  server/utils/utils.go
  server/utils/utils_test.go
Labels: 4. to release

#85 Add store
  Makefile
  server/plugin/api.go
  server/plugin/api_test.go
  server/plugin/command.go
  server/plugin/command_test.go
  server/plugin/configuration_test.go
  server/plugin/plugin.go
  server/plugin/plugin_test.go
  server/plugin/versions.go
  server/poll/poll.go
  server/poll/poll_test.go
  server/poll/transform.go
  server/poll/transform_test.go
  server/store/kvstore/poll.go
  server/store/kvstore/poll_test.go
  server/store/kvstore/store.go
  server/store/kvstore/store_test.go
  server/store/kvstore/system.go
  server/store/kvstore/system_test.go
  server/store/kvstore/upgrade.go
  server/store/kvstore/upgrade_test.go
  server/store/mockstore/mocks/PollStore.go
  server/store/mockstore/mocks/SystemStore.go
  server/store/mockstore/store.go
  server/store/store.go
  server/utils/testutils/data.go
Labels: 4. to release

#94 Release 1.0.0
  plugin.json
  server/plugin/manifest.go
Labels: 4. to release

#97 Fix release file name for deploy
  .travis.yml
Labels: 4. to release, Release

#98 Bump version to 1.0.1
  plugin.json
  server/plugin/manifest.go
Labels: 4. to release, Release

#99 Add Contributing section
  README.md
Labels: 4. to release, enhancement

#100 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 4. to release
