Repository matterpoll/matterpoll, pull requests merged in 2018-08, with the labels that each got.

#20 Add api version to poll endpoints
  server/command_test.go
  server/poll.go
  server/versions.go
Labels: 4. to release, bug

#22 Link executables static
  Makefile
Labels: 3. to review

#23 Release v0.0.2
  CHANGELOG.md
  plugin.json
Labels: 3. to review

#26 Build releases with travis
  .travis.yml
Labels: 2. developing

#30 update api_key
  .travis.yml
Labels: 4. to release

#34 Add info to /
  server/handler.go
  server/handler_test.go
  server/plugin.go
Labels: 3. to review

#36 Bump go version to 1.11
  .travis.yml
Labels: 3. to review, enhancement

#37 Improve installation notes
  README.md
Labels: 4. to release

#40 Add logging
  server/command.go
  server/command_test.go
  server/handler_test.go
  server/plugin.go
Labels: 4. to release

#24 Add config option for trigger
  plugin.json
  server/command.go
  server/command_test.go
  server/configuration.go
  server/configuration_test.go
  server/handler.go
  server/plugin.go
  server/plugin_test.go
  server/utils.go
  server/utils_test.go
Labels: 4. to release, Do not merge

#41 Rename to Matterpoll
  README.md
  server/handler.go
Labels: 3. to review

#42 Simplify logging a bit
  server/handler_test.go
  server/plugin.go
Labels: 4. to release

#45 Fix command error messages
  server/command.go
  server/command_test.go
Labels: 4. to release, bug
