Repository matterpoll/matterpoll, pull requests merged in 2018-09, with the labels that each got.

#47 Add CreatedAt field to Poll
  build/manifest/Gopkg.toml
  server/Gopkg.lock
  server/Gopkg.toml
  server/command_test.go
  server/plugin_test.go
  server/poll.go
  server/poll_test.go
Labels: 4. to release

#33 Show how many pepole have voted
  server/command.go
  server/command_test.go
  server/configuration.go
  server/configuration_test.go
  server/handler.go
  server/handler_test.go
  server/plugin.go
  server/poll.go
Labels: 4. to release

#48 Serve user icon from local assets
  Makefile
  server/command.go
  server/command_test.go
  server/handler_test.go
  server/plugin.go
  server/poll.go
Labels: 4. to release

#49 Update Mattermost to 5.3
  README.md
  build/manifest/Gopkg.lock
  build/manifest/Gopkg.toml
  build/manifest/vendor/github.com/mattermost/mattermost-server/model/channel.go
  build/manifest/vendor/github.com/mattermost/mattermost-server/model/client4.go
  build/manifest/vendor/github.com/mattermost/mattermost-server/model/config.go
  build/manifest/vendor/github.com/mattermost/mattermost-server/model/post.go
  build/manifest/vendor/github.com/mattermost/mattermost-server/model/search_params.go
  build/manifest/vendor/github.com/mattermost/mattermost-server/model/team.go
  build/manifest/vendor/github.com/mattermost/mattermost-server/model/utils.go
  build/manifest/vendor/github.com/mattermost/mattermost-server/model/version.go
  build/manifest/vendor/github.com/mattermost/mattermost-server/utils/markdown/autolink.go
  build/manifest/vendor/github.com/mattermost/mattermost-server/utils/markdown/html.go
  build/manifest/vendor/github.com/mattermost/mattermost-server/utils/markdown/inlines.go
  server/Gopkg.lock
  server/Gopkg.toml
  server/command_test.go
  server/handler.go
  server/handler_test.go
  server/poll.go
Labels: 3. to review

#53 Respect Teammate Name Display
  server/command.go
  server/command_test.go
  server/handler.go
  server/plugin.go
Labels: 3. to review

#64 Add link to repository in settings footer
  plugin.json
Labels: 4. to release

#66 Fix user icon with subpath
  server/handler.go
  server/handler_test.go
  server/plugin.go
Labels: 4. to release

#63 Release 0.1
  CHANGELOG.md
  plugin.json
Labels: 4. to release, Do not merge, Release

#69 Include plugin version in info message
  Makefile
  build/manifest/main.go
  build/setup.mk
  server/handler.go
  server/manifest.go
Labels: 4. to release, enhancement

#67 Add Troubleshooting for https
  README.md
Labels: 3. to review, enhancement

#70 Fix trigger word in README
  README.md
Labels: 4. to release

#68 Refactoring
  server/Gopkg.lock
  server/Gopkg.toml
  server/api.go
  server/api_test.go
  server/command.go
  server/command_test.go
  server/configuration_test.go
  server/idGenerator.go
  server/idGenerator_test.go
  server/plugin.go
  server/plugin_test.go
  server/poll.go
  server/poll_test.go
  server/utils_test.go
Labels: 4. to release

#46 Add message notifying that poll has ended
  server/api.go
  server/api_test.go
  server/command_test.go
  server/plugin_test.go
Labels: 4. to release

#76 Specify http method & cache user image
  server/api.go
  server/api_test.go
Labels: 4. to release

#77 Allow System Admins to delete and end polls
  server/api.go
  server/api_test.go
  server/plugin.go
Labels: 3. to review
