Repository matterpoll/matterpoll, pull requests merged in 2018-11, with the labels that each got.

#103 Add template parameter to links in README.md
  README.md
Labels: 4. to release

#102 Don't post ephemeral message if query is invalid
  server/plugin/command.go
  server/plugin/command_test.go
Labels: 4. to release

#105 Serve logo relative to executable path
  Makefile
  server/plugin/api.go
  server/plugin/api_test.go
Labels: 4. to release

#106 Bump version to 1.0.2
  plugin.json
  server/plugin/manifest.go
Labels: 3. to review, Release

#108 Spring cleanup
  server/plugin/api.go
  server/plugin/plugin.go
  server/store/kvstore/poll.go
  server/store/kvstore/store.go
  server/store/kvstore/system.go
  server/store/kvstore/upgrade.go
  server/store/store.go
  server/utils/testutils/data.go
  server/utils/utils.go
Labels: 4. to release, technical debt

#109 Don't set database schema to patch versions
  server/store/kvstore/upgrade.go
  server/store/kvstore/upgrade_test.go
Labels: 4. to release

#114 Fix command hint text
  server/plugin/command.go
Labels: 4. to release, enhancement
