Repository matterpoll/matterpoll, pull requests merged in 2019-10, with the labels that each got.

#229 Update active.ja.json
  assets/i18n/active.ja.json
Labels: 4. To Release

#224 Release 1.3.0
  plugin.json
  server/plugin/manifest.go
  server/store/kvstore/store_test.go
  server/store/kvstore/upgrade.go
  webapp/src/manifest.js
Labels: 4. To Release, Do Not Merge

#235 Remove superfluous header call
  server/plugin/api.go
Labels: 4. To Release, Bug

#232 Use Default Client Language instead of Default Server Language
  server/plugin/i18n.go
  server/plugin/plugin_test.go
  server/utils/testutils/data.go
Labels: 3. To Review, Enhancement

#233 Update webapp depencies
  webapp/package-lock.json
Labels: 4. To Release

#209 Fix end poll link in DM
  server/plugin/api.go
  server/plugin/api_test.go
Labels: 3. To Review
