Repository matterpoll/matterpoll, pull requests merged in 2019-08, with the labels that each got.

#179 🌐 Update FR translation for 1.2.0
  assets/i18n/active.fr.json
Labels: 4. To Release

#191 MM-17366: handle curly quotes when parsing
  server/utils/utils.go
  server/utils/utils_test.go
Labels: 3. To Review, Bug

#180 Remove Travis
  .travis.yml
  README.md
Labels: 4. To Release

#183 Various code fixes
  server/plugin/api_test.go
  server/plugin/command_test.go
  server/plugin/plugin_test.go
  server/poll/poll_test.go
  server/store/kvstore/store_test.go
Labels: 4. To Release

#188 Use bot account for ephemeral posts
  server/plugin/api.go
  server/plugin/api_test.go
Labels: 4. To Release

#190 Rewrite DB upgrade
  server/store/kvstore/store.go
  server/store/kvstore/store_test.go
  server/store/kvstore/upgrade.go
  server/store/kvstore/upgrade_test.go
Labels: 4. To Release

#193 Add tests for add option api endpoints
  server/plugin/api.go
  server/plugin/api_test.go
Labels: 4. To Release

#200 Update ja translation for release 1.2.0
  assets/i18n/active.ja.json
Labels: 4. To Release

#160 Improve poll UI
  Makefile
  plugin.json
  server/plugin/api.go
  server/plugin/api_test.go
  server/plugin/command.go
  server/plugin/command_test.go
  server/plugin/configuration.go
  server/plugin/configuration_test.go
  server/plugin/plugin.go
  server/plugin/plugin_test.go
  server/poll/poll.go
  server/poll/poll_test.go
  webapp/.babelrc
  webapp/.eslintrc.json
  webapp/.gitignore
  webapp/package-lock.json
  webapp/package.json
  webapp/src/action_types/index.js
  webapp/src/actions/config.js
  webapp/src/actions/vote.js
  webapp/src/actions/vote.test.js
  webapp/src/client/client.js
  webapp/src/client/index.js
  webapp/src/components/post_type/__snapshots__/post_type.test.jsx.snap
  webapp/src/components/post_type/action_view/__snapshots__/action_view.test.jsx.snap
  webapp/src/components/post_type/action_view/action_button/__snapshots__/action_button.test.jsx.snap
  webapp/src/components/post_type/action_view/action_button/action_button.jsx
  webapp/src/components/post_type/action_view/action_button/action_button.test.jsx
  webapp/src/components/post_type/action_view/action_button/index.js
  webapp/src/components/post_type/action_view/action_view.jsx
  webapp/src/components/post_type/action_view/action_view.test.jsx
  webapp/src/components/post_type/action_view/index.js
  webapp/src/components/post_type/fields/fields_table.jsx
  webapp/src/components/post_type/index.js
  webapp/src/components/post_type/post_type.jsx
  webapp/src/components/post_type/post_type.test.jsx
  webapp/src/index.js
  webapp/src/manifest.js
  webapp/src/plugin.jsx
  webapp/src/reducers/index.js
  webapp/src/reducers/post_type.js
  webapp/src/reducers/post_type.test.js
  webapp/src/reducers/vote.js
  webapp/src/reducers/vote.test.js
  webapp/src/selector.js
  webapp/src/utils/link_only_renderer.js
  webapp/src/utils/link_only_renderer.test.js
  webapp/src/utils/remove_markdown.js
  webapp/tests/setup.js
  webapp/webpack.config.js
Labels: 4. To Release

#207 Make webapp code private
  webapp/package.json
Labels: 4. To Release

#186 1.2.0 Docs
  CONTRIBUTING.md
  README.md
Labels: 4. To Release

#185 Release 1.2.0
  .gitattributes
  build/manifest/main.go
  plugin.json
  server/plugin/manifest.go
  server/plugin/plugin.go
  server/store/kvstore/store_test.go
  server/store/kvstore/upgrade.go
Labels: 4. To Release

#181 Leverage relative action URLs
  plugin.json
  server/plugin/api.go
  server/plugin/api_test.go
  server/plugin/command.go
  server/plugin/command_test.go
  server/poll/transform.go
  server/poll/transform_test.go
  webapp/src/manifest.js
Labels: 4. To Release

#208 Fix ci settings
  .circleci/config.yml
Labels: 4. To Release, Bug

#202 Update dependencies
  go.mod
  go.sum
Labels: 3. To Review

#214 Fix version in info endpoint
  server/plugin/api.go
Labels: 4. To Release

#195 Add Golangci lint config
  .golangci.yml
  server/plugin/command_test.go
  server/plugin/configuration.go
  server/plugin/configuration_test.go
  server/plugin/i18n_test.go
  server/poll/poll.go
  server/poll/transform.go
  server/store/kvstore/upgrade.go
  server/utils/utils.go
Labels: 4. To Release
