Repository matterpoll/matterpoll, pull requests merged in 2019-06, with the labels that each got.

#162 Refactor api.go
  server/plugin/api.go
  server/plugin/api_test.go
  server/plugin/command.go
  server/plugin/plugin_test.go
Labels: 4. To Release

#161 Trim space when checking duplication
  server/poll/poll.go
  server/poll/poll_test.go
Labels: 4. To Release

#163 Secure API request via Mattermost-User-ID header
  server/plugin/api.go
  server/plugin/api_test.go
Labels: 4. To Release, Enhancement

#164 Remove unneeded UnregisterCommand call
  server/plugin/plugin.go
  server/plugin/plugin_test.go
Labels: 4. To Release, Enhancement

#166 Add contribution guideline
  CONTRIBUTING.md
  README.md
Labels: 3. To Review

#169 Add Circleci
  .circleci/config.yml
  .travis.yml
  README.md
Labels: 4. To Release
