Repository matterpoll/matterpoll, pull requests merged in 2019-04, with the labels that each got.

#144 Don't start plugin if siteURL is not set
  server/plugin/configuration.go
  server/plugin/plugin.go
  server/plugin/plugin_test.go
Labels: 4. to release

#145 Add FR translation
  assets/i18n/active.fr.json
Labels: 3. to review

#146 Fix NPE in addOption
  server/plugin/api.go
Labels: 3. to review, bug

#149 Add japanese translation
  assets/i18n/active.ja.json
Labels: 4. to release

#151 Fix translations
  assets/i18n/active.de.json
  assets/i18n/active.en.json
  assets/i18n/active.fr.json
  assets/i18n/active.ja.json
Labels: 3. to review, bug

#152 Add 1.1.0 docs
  README.md
Labels: 3. to review

#150 Release 1.1.0
  plugin.json
  server/Gopkg.lock
  server/Gopkg.toml
  server/plugin/manifest.go
  server/plugin/plugin.go
Labels: 4. to release, Do Not Merge, Release
