Repository matterpoll/matterpoll, pull requests merged in 2020-10, with the labels that each got.

#246 Prevent spoofing of requests
  server/plugin/api.go
  server/plugin/api_test.go
  server/plugin/command.go
  server/plugin/command_test.go
  server/poll/poll.go
  server/utils/testutils/data.go
Labels: 4. To Release

#256 Implement "--votes=X" setting for multi answer
  server/plugin/api.go
  server/plugin/api_test.go
  server/plugin/command.go
  server/plugin/command_test.go
  server/plugin/i18n_test.go
  server/plugin/plugin_test.go
  server/poll/poll.go
  server/poll/poll_test.go
  server/poll/transform.go
  server/poll/transform_test.go
  server/store/kvstore/poll.go
  server/store/kvstore/poll_test.go
  server/store/kvstore/store_test.go
  server/store/kvstore/upgrade.go
  server/store/kvstore/upgrade_test.go
  server/store/mockstore/mocks/PollStore.go
  server/store/store.go
  server/utils/testutils/data.go
  server/utils/testutils/mock.go
  server/utils/utils_test.go
Labels: 4. To Release, Docs/Needed, Tech/Server

#331 Update German translation for 1.4.0
  assets/i18n/active.de.json
  assets/i18n/active.en.json
  assets/i18n/active.es.json
  assets/i18n/active.ko.json
  assets/i18n/active.zh-CN.json
  server/poll/poll.go
Labels: 4. To Release, Type/Translation

#329 Fix indentation in plugin.json
  plugin.json
Labels: 4. To Release

#327 Post responses in RHS
  server/plugin/api.go
  server/plugin/api_test.go
  server/plugin/command.go
  server/plugin/command_test.go
  server/plugin/plugin.go
Labels: 4. To Release

#333 update ja translation
  assets/i18n/active.ja.json
Labels: 4. To Release, Type/Translation

#332 Update Simplified Chinese translation for 1.4.0
  assets/i18n/active.zh-CN.json
Labels: 4. To Release, Type/Translation

#330 🌐 Update FR translation for 1.4.0
  assets/i18n/active.fr.json
Labels: 3. To Review, Type/Translation

#338 Update Traditional Chinese translation for 1.4.0
  assets/i18n/active.zh-TW.json
Labels: 4. To Release, Type/Translation

#337 Show default message if translation is missing
  server/plugin/i18n.go
Labels: 4. To Release

#335 Fix how to check duplicated vote with multi votes setting
  server/poll/poll.go
  server/poll/poll_test.go
Labels: 4. To Release

#339 Update Spanish translation for 1.4.0
  assets/i18n/active.es.json
Labels: 4. To Release, Type/Translation

#340 🌐🐛 Fix FR translation
  assets/i18n/active.fr.json
Labels: 4. To Release, Type/Translation

#344 fix typo in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: 4. To Release, Type/Documenation

#343 Update KR Translation for 1.4.0
  assets/i18n/active.ko.json
Labels: 4. To Release, Type/Translation

#357 update Polish translation for 1.4.0
  assets/i18n/active.pl.json
Labels: 4. To Release, Type/Translation
