Repository matterpoll/matterpoll, pull requests merged in 2020-05, with the labels that each got.

#293 Add instructions for development
  CONTRIBUTING.md
Labels: 4. To Release, Type/Documenation

#292 Show "Add Option" button for only users who have permission
  server/plugin/api_test.go
  server/poll/metadata.go
  server/poll/metadata_test.go
  server/poll/poll.go
  webapp/src/actions/poll_metadata.js
  webapp/src/components/post_type/action_view/__snapshots__/action_view.test.jsx.snap
  webapp/src/components/post_type/action_view/action_view.jsx
  webapp/src/components/post_type/action_view/action_view.test.jsx
  webapp/src/reducers/poll_metadata.test.js
Labels: 4. To Release, Tech/Webapp, Type/Enhancement

#296 Bump github.com/blang/semver to v4
  go.mod
  go.sum
  server/plugin/plugin.go
  server/plugin/plugin_test.go
  server/store/kvstore/upgrade.go
  server/store/kvstore/upgrade_test.go
Labels: 4. To Release
