Repository matterpoll/matterpoll, pull requests merged in 2020-09, with the labels that each got.

#315 add Chinese translation
  CONTRIBUTING.md
  README.md
  assets/i18n/active.zh-CN.json
Labels: 4. To Release

#313 Format field title in attachments
  webapp/src/components/post_type/__snapshots__/post_type.test.jsx.snap
  webapp/src/components/post_type/action_view/action_button/__snapshots__/action_button.test.jsx.snap
  webapp/src/components/post_type/fields/__snapshots__/fields_table.test.jsx.snap
  webapp/src/components/post_type/fields/fields_table.jsx
  webapp/src/components/post_type/fields/fields_table.test.jsx
  webapp/tests/setup.js
Labels: 3. To Review, Type/Bug

#322 Add Traditional Chinese Language
  CONTRIBUTING.md
  README.md
  assets/i18n/active.zh-TW.json
Labels: 4. To Release, Docs/Done

#321 Register Command in OnActivate
  server/plugin/plugin.go
  server/plugin/plugin_test.go
Labels: 4. To Release, Docs/Not Needed

#301 Add Korean(ko) translation
  CONTRIBUTING.md
  README.md
  assets/i18n/active.ko.json
Labels: 3. To Review, Docs/Done

#304 Set voter count to Metadata when progress option was set
  server/poll/poll.go
  server/poll/poll_test.go
  server/poll/transform.go
Labels: 4. To Release, Type/Bug

#308 Fix tests for #246
  server/plugin/api_test.go
  server/plugin/command_test.go
  server/utils/testutils/data.go
Labels: 4. To Release
