Repository matterpoll/matterpoll, pull requests merged in 2020-11, with the labels that each got.

#353 Disable dependabot
  .github/dependabot.yml
Labels: 4. To Release, Type/Tools

#360 Update description
  plugin.json
  server/plugin/manifest.go
Labels: 4. To Release, Type/Enhancement

#346 update README for 1.4.0
  README.md
  images/screenshot.png
Labels: 4. To Release, Type/Documenation

#347 Release 1.4.0
  plugin.json
  server/plugin/manifest.go
Labels: 4. To Release

#354 #349 Remove checkServerVersion
  server/plugin/plugin.go
  server/plugin/plugin_test.go
Labels: 4. To Release

#351 Refactor variable names
  server/plugin/api.go
  server/plugin/api_test.go
  server/plugin/plugin.go
  server/poll/metadata.go
  server/poll/metadata_test.go
  server/poll/poll.go
  server/poll/poll_test.go
  webapp/src/actions/poll_metadata.js
  webapp/src/components/post_type/action_view/__snapshots__/action_view.test.jsx.snap
  webapp/src/components/post_type/action_view/action_view.jsx
  webapp/src/components/post_type/action_view/action_view.test.jsx
  webapp/src/reducers/poll_metadata.test.js
Labels: 4. To Release, Docs/Not Needed

#362 Allow empty string as third option in modal
  server/plugin/api.go
Labels: 3. To Review
