Repository matterpoll/matterpoll, pull requests merged in 2020-03, with the labels that each got.

#263 Make use of EnsureBotOption
  server/plugin/plugin.go
  server/plugin/plugin_test.go
Labels: 3. To Review

#264 Use deterministic post action ids
  go.mod
  go.sum
  plugin.json
  server/plugin/plugin.go
  server/poll/transform.go
  server/poll/transform_test.go
Labels: 4. To Release

#259 Add missing translations for polish
  assets/i18n/active.pl.json
Labels: 4. To Release

#220 Allow creating of poll via interactive dialog
  assets/i18n/active.de.json
  assets/i18n/active.en.json
  assets/i18n/active.fr.json
  assets/i18n/active.ja.json
  assets/i18n/active.pl.json
  server/plugin/api.go
  server/plugin/api_test.go
  server/plugin/command.go
  server/plugin/command_test.go
Labels: 4. To Release, Docs/Needed

#266 Use json.Encoder to write json responses
  server/plugin/api.go
Labels: 4. To Release, Technical Debt

#268 Add test for Metadata.ToMap()
  server/poll/metadata.go
  server/poll/metadata_test.go
Labels: 3. To Review, Type/Technical Debt

#273 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: 4. To Release, Type/Documenation

#272 Add spanish translation
  CONTRIBUTING.md
  README.md
  assets/i18n/active.es.json
Labels: 4. To Release, Type/Enhancement

#275 Update dependencies
  go.mod
  go.sum
  webapp/package-lock.json
  webapp/package.json
Labels: 3. To Review, Type/Enhancement

#276 Fix races for concurrent votes
  server/plugin/api.go
  server/plugin/api_test.go
  server/plugin/command.go
  server/plugin/command_test.go
  server/store/kvstore/poll.go
  server/store/kvstore/poll_test.go
  server/store/mockstore/mocks/PollStore.go
  server/store/store.go
Labels: 3. To Review
