Repository matterpoll/matterpoll, pull requests merged in 2022-06, with the labels that each got.

#430 Fix ci error
  .circleci/config.yml
Labels: Type/Bug, 3. To Review, Type/Tools, Docs/Not Needed

#421 translate ja
  assets/i18n/active.ja.json
Labels: 3. To Review, Type/Translation

#432 Update active.de.json
  assets/i18n/active.de.json
Labels: 4. To Release, Type/Translation

#422 Updates for 1.5.0
  CONTRIBUTING.md
  README.md
  go.mod
  images/screenshot.png
  plugin.json
  server/plugin/manifest.go
  server/store/kvstore/store_test.go
  server/store/kvstore/upgrade.go
Labels: 3. To Review, Type/Release
