Repository matterpoll/matterpoll, pull requests merged in 2022-10, with the labels that each got.

#453 Use version of React DOM provided by web app
  webapp/webpack.config.js
Labels: 4. To Release, Type/Technical Debt, Work In Progress, Docs/Not Needed, Tech/Webapp

#455 Update CI orb to latest version
  .circleci/config.yml
  .golangci.yml
  .nvmrc
  server/plugin/api_test.go
  server/plugin/plugin_test.go
  server/utils/i18n.go
Labels: 4. To Release, Type/Tools, Docs/Not Needed

#457 Fix grammar in translation (de)
  assets/i18n/active.de.json
Labels: 4. To Release, Docs/Not Needed
