Repository matterpoll/matterpoll, pull requests merged in 2023-05, with the labels that each got.

#477 translate ja
  assets/i18n/active.ja.json
Labels: 4. To Release, Type/Translation

#479 Updates for 1.6
  CONTRIBUTING.md
  README.md
  plugin.json
  server/store/kvstore/store_test.go
  server/store/kvstore/upgrade.go
Labels: 4. To Release, Type/Release

#484 Minor typo
  README.md
Labels: 4. To Release, Type/Documenation

#487 Disable CGO
  Makefile
Labels: 4. To Release, Type/Technical Debt

#488 Updates for 1.6.1
  plugin.json
  server/store/kvstore/store_test.go
  server/store/kvstore/upgrade.go
Labels: 4. To Release, Type/Release
