Repository matterpoll/matterpoll, pull requests merged in 2023-04, with the labels that each got.

#478 Update the Simplified Chinese translation for 1.6.0
  assets/i18n/active.zh-CN.json
Labels: 3. To Review, Type/Translation

#480 Update the Traditional Chinese translation for 1.6
  assets/i18n/active.zh-TW.json
Labels: 4. To Release, Type/Translation

#481 🌐 Update FR translation for 1.6.0 (#476)
  assets/i18n/active.fr.json
Labels: 4. To Release, Type/Translation

#482 Update Spanish translation for 1.6
  assets/i18n/active.es.json
Labels: 4. To Release, Type/Translation

#483 Update German Translation for 1.6.0
  assets/i18n/active.de.json
Labels: 4. To Release
