Repository matterpoll/matterpoll, pull requests merged in 2023-11, with the labels that each got.

#512 Add plugin file size upload issue solution in README.md
  README.md
Labels: 4. To Release, Type/Documenation

#513 fix: inconsistent capitalization in "Reset your vote"
  assets/i18n/active.en.json
  server/poll/transform.go
  server/poll/transform_test.go
  webapp/src/components/post_type/action_view/__snapshots__/action_view.test.jsx.snap
  webapp/src/components/post_type/action_view/action_view.test.jsx
Labels: 4. To Release, Docs/Needed

#516 Add notes regarding Mobile app not supporting ExperimentalUI
  README.md
Labels: 4. To Release, Type/Documenation

#520 Add missing executables to plugin.json
  plugin.json
Labels: Type/Enhancement, 4. To Release, Docs/Not Needed
