Repository matterpoll/matterpoll, pull requests merged in 2024-05, with the labels that each got.

#543 Updates for 1.7
  images/screenshot.png
  plugin.json
  server/store/kvstore/store_test.go
  server/store/kvstore/upgrade.go
Labels: 4. To Release, Type/Release

#548 Update the Simplified Chinese translation for 1.7.0
  assets/i18n/active.zh-CN.json
Labels: 4. To Release, Type/Translation

#547 translate ja
  assets/i18n/active.en.json
  assets/i18n/active.ja.json
Labels: 4. To Release, Type/Translation

#550 Update the Traditional Chinese translation for 1.7.0
  assets/i18n/active.zh-TW.json
Labels: 3. To Review, Type/Translation

#551 🌐 — Update FR translation for 1.7.0 (#546)
  assets/i18n/active.fr.json
Labels: 4. To Release, Type/Translation

#552 German translation for Release 1.7.0 #546
  assets/i18n/active.de.json
Labels: 4. To Release, Type/Translation

#553 Update Spanish translation for 1.7.0
  assets/i18n/active.es.json
Labels: 4. To Release, Type/Translation

#554 Update russian translates for 1.7.0
  assets/i18n/active.ru.json
Labels: 4. To Release, Type/Translation

#555 Introduce community-plugin-ci/cd.yml
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: 4. To Release, Type/Tools, Docs/Not Needed
