Repository matterpoll/matterpoll, pull requests merged in 2025-02, with the labels that each got.

#579 Update the Simplified Chinese translation for 1.8.0
  assets/i18n/active.zh-CN.json
Labels: 4. To Release, Type/Translation

#581 Update the Traditional Chinese translation for 1.8.0
  assets/i18n/active.zh-TW.json
Labels: 4. To Release, Type/Translation

#580 Update the Korean translation for 1.8.0
  assets/i18n/active.ko.json
Labels: 3. To Review, Type/Translation

#583 Update the Swedish translation for 1.8.0
  assets/i18n/active.sv.json
Labels: 4. To Release, Type/Translation

#577 Update the Japanese translation for 1.8.0
  assets/i18n/active.ja.json
Labels: 4. To Release, Type/Translation

#585 Update Spanish translation for 1.8.0
  assets/i18n/active.es.json
Labels: 4. To Release

#586 Update active.ru.json
  assets/i18n/active.ru.json
Labels: 4. To Release, Type/Translation
